### ISSUE TITLE
Sometimes orpheus isn't on the homepage.

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#1151] opened 2023-09-25 17:41 UTC
Sometimes the page loads and looks like this.

![Screenshot 2023-09-25 at 1 24 48 PM](https://github.com/hackclub/sprig/assets/27078897/234079d3-c201-456d-85ae-267cfb9472b9)

When it should have orpheus in the corner.

![Screenshot 2023-09-22 at 5 35 37 PM](https://github.com/hackclub/sprig/assets/27078897/1ee67314-2457-484a-bef2-7af29acd5e74)

This ^ image shows the hovered state.

**Comment by LucasHT22** [comment] 2023-09-25 18:00
I didn't even know it existed haha

**Comment by BrightTheBackpack** [comment] 2023-11-04 18:04
I couldn't really reproduce this issue. Does it disappear at random?

**Comment by BrightTheBackpack** [comment] 2023-11-09 19:02
Looks like it might have something to do with the dimensions of your screen. If the width of the screen is too small, it will not appear. I will investigate further and try to find a fix.

**Comment by grymmy** [comment] 2023-11-20 18:07
@BrightTheBackpack yes, I can confirm - I see it appearing and disappearing based on the aspect ratio of the screen - in portrait, it doesn't show up (probably offscreen?)

**Comment by grymmy** [comment] 2023-11-20 18:09
@LucasHT22 any chance you could look into this one?  if not, please assign it back to me and I'll find a better home

**Comment by LucasHT22** [comment] 2023-11-26 04:21
Looks like this is on purpose:
![image](https://github.com/hackclub/sprig/assets/88567622/9f45287b-b987-4e16-845b-f2d0bd6ef4be)

**Comment by JosiasAurel** [comment] 2023-12-06 12:18
@leomcelroy do we still want this to always be shown on the homepage? 
Why is this not visible on some displays @kognise ?

**Comment by JosiasAurel** [comment] 2023-12-06 12:19
@leomcelroy do we still want this to be shown on the homepage?

**Comment by grymmy** [comment] 2023-12-06 13:54
@JosiasAurel @LucasHT22 given @leomcelroy opened the bug somewhat recently I think we should just fix the issue and make it display bottom-left as expected

**Closed** 2023-12-07 13:09 UTC
Labels: bug
