### ISSUE TITLE
3d Sprig console movement delay

### ISSUE THREAD

**Issue by Shrey-Mehra** [hackclub/sprig#894] opened 2023-03-03 12:25 UTC
Delay in the movement of the sprig console

**Comment by LucasHT22** [comment] 2023-03-03 16:21
could you give more details?

**Comment by Shrey-Mehra** [comment] 2023-03-04 15:54
Hey Lucas, the Sprig console in Home page is an moveable item, and the movement of it is slightly delayed, it probably could be because of delay in page loading in general but that is an issue.

**Comment by SamDev-7** [comment] 2023-03-12 00:35
I cannot reproduce this issue, there is no delay for me?
We recently updated the UI for Sprig, can you check again if this is still an issue on your side? @Shrey-Mehra

**Comment by Shrey-Mehra** [comment] 2023-03-13 13:45
Hey Sam,
i checked the sprig it working fine

**Comment by karamassie** [comment] 2023-03-15 17:00
closed as no repro

**Comment by kognise** [comment] 2023-03-15 17:01
—the 3d model needs time to load in, can't really magically solve this

**Closed by karamassie** 2023-03-15 17:00 UTC
Labels: bug
