### ISSUE TITLE
A new sprigfuzzy for `/games`

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/sprig#1024] opened 2023-05-11 16:28 UTC
The current version of the test, a.k.a sprigfuzzy, located in the folder [`/test`](https://github.com/hackclub/sprig/blob/main/tests/sprigfuzzy.js) it's outdated, without the test running, we aren't sure if the game will run on the console

**Comment by grymmy** [comment] 2023-12-18 18:12
Closing as duplicate of https://github.com/hackclub/sprig/issues/1104

**Closed by grymmy** 2023-12-18 18:12 UTC
Labels: feature request
