### ISSUE TITLE
Increase range on Sprig screen resizing.

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#828] opened 2023-02-22 18:20 UTC
Max can be aspect ratio which fits screen on page but it can definitely go smaller.

**Comment by grymmy** [comment] 2023-03-02 16:55
@leomcelroy Do you have any criteria here for how much the range should be increased, or would any gain be sufficient? (how much would be good enough to satisfy this request?)

**Comment by alhardwarehyde** [comment] 2023-03-03 16:00
Closing this out because it is a duplicate of this one: https://github.com/orgs/hackclub/projects/32/views/2?filterQuery=no%3Apriority+no%3Acomplexity+is%3Aopen+-Status%3ADone+no%3Aassignee&pane=issue&itemId=21414624 which has a clearer ask.

**Closed by alhardwarehyde** 2023-03-03 16:00 UTC
Labels: Sprig 2.0
