### ISSUE TITLE
Allow key rebinding on web interface

### ISSUE THREAD

**Issue by dhouck** [hackclub/sprig#499] opened 2022-11-05 22:27 UTC
For people with non-QWERTY keyboard layouts, having to play with WASD instead of (eg.) ,AOE or ZQSD can be difficult.

**Comment by grymmy** [comment] 2023-03-07 14:46
@alhardwarehyde Hmm we missed this in triage, we should make sure there aren't any others...

**Comment by grymmy** [comment] 2023-03-17 19:56
Closed as duplicate of #915.

**Closed by grymmy** 2023-03-17 19:56 UTC
Labels: feature request
