### ISSUE TITLE
feedback: Map editor is so confusing because there's no grid lines... I couldn't figure out what to do after opening it for the first time, and it's also hard to count how many rows/columns there are.

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#146] opened 2022-07-20 14:42 UTC
from @maggie-j-liu

**Comment by leomcelroy** [comment] 2022-07-28 16:38
Duplicate of [this issue](https://github.com/hackclub/sprig/issues/115).

**Closed by leomcelroy** 2022-07-28 16:38 UTC
