### ISSUE TITLE
Problem with Sprig game editor...?

### ISSUE THREAD

**Issue by apzzd** [hackclub/sprig#610] opened 2022-12-03 16:44 UTC
Hi - I think I might have found a problem with the editor part of the website - when I try to open a game from the gallery (e.x. https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/getting_started.js) or go to the "Editor" tab on the home screen (https://editor.sprig.hackclub.com) only the background image shows and the following error is in the console when I inspect the page:

```
ReferenceError: Can't find variable: OffscreenCanvas
```

Not sure why this is...yesterday the editor worked, but today for some reason it started doing this.

<img width="1221" alt="error-screenshot" src="https://user-images.githubusercontent.com/59454160/205452434-0a67e44f-c185-4d20-9a2d-083ede825722.png">

**Comment by Omay238** [comment] 2022-12-03 19:59
I'm not able to reproduce this error. Can you send a video of how you're getting it?

**Comment by apzzd** [comment] 2022-12-04 15:11
yeah, sure!

**Comment by apzzd** [comment] 2022-12-04 15:13
https://user-images.githubusercontent.com/59454160/205498730-233e5294-e7a4-4547-a1f8-4bfeaf269bab.mov

Here's the video.

**Comment by apzzd** [comment] 2022-12-04 15:20
This works in Firefox 107.0.1, but not in Safari 16.1 for some reason.

**Comment by leomcelroy** [comment] 2022-12-04 15:55
Ahh offscreen canvas isn't supported in safari. We can fix this up. Thanks for letting us know

**Comment by apzzd** [comment] 2022-12-04 17:04
Ok, thanks so much!

**Comment by leomcelroy** [comment] 2022-12-05 03:52
Should be fixed!

**Closed by leomcelroy** 2022-12-05 03:52 UTC

**Comment by apzzd** [comment] 2022-12-05 14:24
Yay, it works! Thank you!

**Comment by dez64ru** [comment] 2023-03-31 10:01
@apzzd now supports

**Comment by dez64ru** [comment] 2023-03-31 10:02
@leomcelroy supports now
