### ISSUE TITLE
Update "Get a Sprig" text and image with new UI

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sprig#871] opened 2023-02-28 20:21 UTC
<img width="1536" alt="Screenshot 2023-02-28 at 3 15 50 PM" src="https://user-images.githubusercontent.com/122998778/221968861-1994f767-c5e9-4618-a22c-258cf237f3c0.png">

**Comment by kognise** [comment] 2023-03-02 16:45
Done + duplicate of #800

**Closed** 2023-03-02 16:45 UTC
Labels: Sprig 2.0
